# To reload this configuration and any rule configurations referenced by this configuration
# do a POST to http://localhost:9090/-/reload.
# In order for on-demand configuration reloading to work, the --web.enable-lifecycle
# option must be specified when launching Prometheus.
global:
  scrape_interval: 10s

rule_files:
  - "/etc/prometheus/rules/*.rules"

scrape_configs:
  - job_name: 'spring_boot_actuator_metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      # The IP address below must be replaced with the current IP address of the computer
      # on which the REST Example application is running.
      # Note that "localhost" or "127.0.0.1" does not work!
      - targets: ['192.168.1.104:8080']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alert-manager:9093
